"""Streamlit entry point for the Career Guidance App."""

import streamlit as st

from career_guidance import __version__
from career_guidance.config import configure_logging, load_settings
from career_guidance.history import GuidanceHistory
from career_guidance.models import InvalidInputError
from career_guidance.suggestions import format_suggestions_markdown, generate_guidance

settings = load_settings()
logger = configure_logging(settings)

st.set_page_config(page_title="Career Guidance AI", page_icon="🎓", layout="wide")


def get_history() -> GuidanceHistory:
    """Return the session-scoped guidance history."""
    if "history" not in st.session_state:
        st.session_state.history = GuidanceHistory()
    return st.session_state.history


def render_guidance_page() -> None:
    """Render the main guidance workflow."""
    st.title("🎓 Career Guidance AI")
    st.caption(f"Version {__version__} · Environment: {settings.app_env}")
    st.markdown(
        "Get tailored career path recommendations from your skills, "
        "resume summary, or interests."
    )

    if not settings.openai_api_key:
        st.info(
            "**Demo mode**: showing curated offline suggestions. "
            "Set `OPENAI_API_KEY` to enable AI-powered analysis."
        )

    skills_input = st.text_area(
        "Paste your skills, resume summary, or interests here:",
        max_chars=settings.max_input_length,
        height=180,
        placeholder=(
            "e.g. 3 years of Python, SQL and dashboarding; "
            "enjoy explaining technical topics..."
        ),
    )

    if st.button("Suggest Career Paths", type="primary"):
        try:
            with st.spinner("Analyzing your profile..."):
                result = generate_guidance(skills_input, settings)
        except InvalidInputError as error:
            st.warning(str(error))
            return
        except Exception:  # noqa: BLE001 - surface a safe message to the user
            logger.exception("Unexpected error while generating suggestions")
            st.error("Something went wrong. Please try again later.")
            return

        get_history().add(skills_input, result)
        if result.used_fallback:
            st.warning(
                "The AI service was unavailable, so curated fallback "
                "suggestions are shown instead."
            )
        st.success(f"Suggestions generated by: {result.provider_name}")
        markdown = format_suggestions_markdown(result.suggestions)
        st.markdown(markdown)
        st.download_button(
            "⬇️ Download as Markdown",
            data=markdown,
            file_name="career-suggestions.md",
            mime="text/markdown",
        )


def render_history_page() -> None:
    """Render the session history with export options."""
    st.title("🕘 Session History")
    history = get_history()

    if len(history) == 0:
        st.info("No suggestions generated yet. Visit **Career Guidance** to get started.")
        return

    col_md, col_json, col_clear = st.columns(3)
    with col_md:
        st.download_button(
            "⬇️ Export Markdown",
            data=history.to_markdown(),
            file_name="guidance-history.md",
            mime="text/markdown",
        )
    with col_json:
        st.download_button(
            "⬇️ Export JSON",
            data=history.to_json(),
            file_name="guidance-history.json",
            mime="application/json",
        )
    with col_clear:
        if st.button("🗑️ Clear history"):
            history.clear()
            st.rerun()

    for entry in reversed(history.entries):
        label = f"{entry.timestamp} · {entry.provider_name} · {entry.input_excerpt}"
        with st.expander(label):
            st.markdown(format_suggestions_markdown(entry.suggestions))


def render_about_page() -> None:
    """Render product information."""
    st.title("ℹ️ About")
    st.markdown(
        f"""
**Career Guidance AI** (v{__version__}) recommends career paths based on your
skills, resume summary, or interests.

- **AI mode**: with `OPENAI_API_KEY` configured, suggestions are generated by an LLM.
- **Demo mode**: without a key, the app runs fully offline with curated suggestions.
- Results are kept in **session history** and can be exported as Markdown or JSON.

No personal data is stored server-side; history lives only in your browser session.
"""
    )


def main() -> None:
    """Render the Streamlit UI."""
    page = st.sidebar.radio("Navigate", ["Career Guidance", "History", "About"])
    st.sidebar.caption(f"v{__version__} · {settings.app_env}")
    if page == "Career Guidance":
        render_guidance_page()
    elif page == "History":
        render_history_page()
    else:
        render_about_page()


if __name__ == "__main__":
    main()
