"use client";

/**
 * `/pathway` — the flagship screen: “I want to become X. Do I qualify?”
 *
 * It answers with the truth (blockers, in one sentence), the maths (skill
 * coverage, preparation level, requirements one by one) and a way forward
 * (real Indian bridge programmes, a phased plan, and the closest careers the
 * user can enter right now). Nothing here is generated by an LLM: every number
 * is computed by the backend engines and carries its source.
 */

import { useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { AlertTriangle, ArrowRight, Check, Compass, GraduationCap, Info, Route, Target } from "lucide-react";
import Link from "next/link";
import { pathway as pathwayApi, type PathwayResult, type LadderRung } from "@/lib/api";
import { useI18n } from "@/lib/i18n";
import { useApi } from "@/lib/use-api";
import { TextEffect, AnimatedGroup, InView } from "./motion";
import { Badge, Button, Card, Empty, ErrorNote, Progress, SourceLabel, Spinner } from "./ui";
import { CareerPicker } from "./career-picker";

const SUGGESTIONS = ["29-1069.03", "23-1011.00", "13-2011.01", "15-1199.08"];

const VERDICT_TONE = {
  eligible: "ok",
  reachable: "accent",
  blocked: "gold",
} as const;

function money(value: number | null | undefined, symbol: string) {
  if (value === null || value === undefined) return "—";
  return `${symbol}${value.toLocaleString("en-IN")}`;
}

export function PathwayView() {
  const { t } = useI18n();
  const signals = useApi(() => pathwayApi.signals(), []);
  const [careerId, setCareerId] = useState("");
  const [resume, setResume] = useState("");
  const [hours, setHours] = useState(6);
  const [result, setResult] = useState<PathwayResult | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function run(id = careerId) {
    if (!id) return;
    setBusy(true);
    setError(null);
    try {
      const payload = await pathwayApi.run({
        career_id: id,
        resume_text: resume.trim(),
        hours_per_week: hours,
      });
      setResult(payload);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }

  if (signals.loading && !signals.data) return <Spinner label={t("pw_running")} />;
  if (signals.error) return <ErrorNote error={signals.error} retry={signals.reload} />;

  return (
    <div className="flex flex-col gap-6">
      <header>
        <TextEffect as="h1" className="font-serif text-3xl sm:text-4xl">
          {t("pw_title")}
        </TextEffect>
        <p className="mt-2 max-w-3xl text-sm text-fg-2">{t("pw_sub")}</p>
        <SourceLabel text={t("pw_source")} />
      </header>

      <Card className="flex flex-col gap-4">
        <div className="grid gap-4 md:grid-cols-2">
          <div>
            <label className="mb-1.5 block text-xs font-medium uppercase tracking-wide text-fg-3">
              {t("pw_target")}
            </label>
            <CareerPicker
              value={careerId || signals.data?.target?.career_id || ""}
              label={signals.data?.target?.title ?? ""}
              placeholder={t("pw_target_ph")}
              onChange={setCareerId}
            />
            <div className="mt-2 flex flex-wrap gap-1.5">
              {SUGGESTIONS.map((id) => (
                <button
                  key={id}
                  type="button"
                  onClick={() => {
                    setCareerId(id);
                    void run(id);
                  }}
                  className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-fg-2 transition hover:border-accent/40 hover:text-fg"
                >
                  {id}
                </button>
              ))}
            </div>
          </div>
          <div>
            <label className="mb-1.5 block text-xs font-medium uppercase tracking-wide text-fg-3">
              {t("pw_resume")}
            </label>
            <textarea
              value={resume}
              onChange={(event) => setResume(event.target.value)}
              placeholder={t("pw_resume_ph")}
              rows={4}
              className="w-full rounded-xl border border-white/10 bg-bg-3/60 px-3 py-2 text-sm text-fg outline-none placeholder:text-fg-3 focus:border-accent/50"
            />
          </div>
        </div>
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div className="w-full max-w-xs">
            <label className="mb-1.5 block text-xs font-medium uppercase tracking-wide text-fg-3">
              {t("pw_hours")}
            </label>
            <input
              type="range"
              min={1}
              max={40}
              value={hours}
              onChange={(event) => setHours(Number(event.target.value))}
              className="w-full accent-[var(--accent)]"
            />
            <p className="mt-1 text-xs text-fg-3">{hours} h</p>
          </div>
          <Button variant="primary" onClick={() => void run()} disabled={busy || !careerId}>
            {busy ? t("pw_running") : t("pw_run")}
          </Button>
        </div>
        {error && <p className="text-sm text-danger">{error}</p>}
      </Card>

      <AnimatePresence mode="wait">
        {busy && <Spinner key="busy" label={t("pw_running")} />}
        {!busy && !result && (
          <Empty
            key="empty"
            title={t("pw_empty_title")}
            hint={t("pw_empty_hint")}
            action={
              <Button
                variant="outline"
                onClick={() => {
                  setCareerId("29-1069.03");
                  void run("29-1069.03");
                }}
              >
                <Compass size={15} /> {t("pw_run")}
              </Button>
            }
          />
        )}
        {!busy && result && <Result key={result.target.id} result={result} />}
      </AnimatePresence>
    </div>
  );
}

function Result({ result }: { result: PathwayResult }) {
  const { t } = useI18n();
  const verdict = result.verdict;
  const tone = VERDICT_TONE[verdict.verdict];
  return (
    <div className="flex flex-col gap-5">
      <Card>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <Badge tone={tone}>
              {verdict.verdict === "eligible"
                ? t("pw_verdict_eligible")
                : verdict.verdict === "reachable"
                  ? t("pw_verdict_reachable")
                  : t("pw_verdict_blocked")}
            </Badge>
            <h2 className="mt-2 font-serif text-2xl">{result.target.title}</h2>
            <p className="mt-1 max-w-2xl text-sm text-fg-2">{verdict.headline}</p>
          </div>
          <div className="flex gap-4">
            <div className="text-right">
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("pw_coverage")}</p>
              <p className="font-serif text-2xl">{verdict.coverage}%</p>
            </div>
            <div className="text-right">
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("pw_zone")}</p>
              <p className="font-serif text-2xl">{verdict.user_zone}</p>
              <p className="text-xs text-fg-3">zone {result.target.job_zone}</p>
            </div>
          </div>
        </div>
        <Progress percent={verdict.coverage} label={`${t("pw_coverage")} ${verdict.coverage}%`} />
        <div className="mt-4 flex flex-wrap gap-2">
          <Button href={`/careers/${result.target.id}`} variant="outline">
            <ArrowRight size={15} /> {t("cr_open")}
          </Button>
          <Button href="/plan" variant="ghost">
            <Route size={15} /> {t("nav_plan")}
          </Button>
        </div>
        <SourceLabel text={verdict.source} />
      </Card>

      <div className="grid gap-5 lg:grid-cols-2">
        <Card>
          <h3 className="font-serif text-xl">{t("pw_requirements")}</h3>
          <ul className="mt-3 flex flex-col gap-2.5">
            {verdict.requirements.map((row) => (
              <li key={row.requirement} className="flex gap-3 text-sm">
                <span
                  className={
                    row.status === "met"
                      ? "mt-0.5 text-ok"
                      : row.status === "partial"
                        ? "mt-0.5 text-gold"
                        : "mt-0.5 text-danger"
                  }
                >
                  {row.status === "met" ? <Check size={16} /> : <AlertTriangle size={16} />}
                </span>
                <div>
                  <p className="text-fg">{row.requirement}</p>
                  <p className="text-fg-3">{row.detail}</p>
                  <SourceLabel text={row.source} />
                </div>
              </li>
            ))}
          </ul>
        </Card>

        <Card className="flex flex-col gap-4">
          {verdict.blockers.length > 0 && (
            <div>
              <h3 className="font-serif text-xl">{t("pw_blockers")}</h3>
              <ul className="mt-2 flex flex-col gap-2 text-sm">
                {verdict.blockers.map((blocker) => (
                  <li key={blocker.text} className="flex gap-2">
                    <Badge tone={blocker.severity === "hard" ? "danger" : "gold"}>
                      {blocker.severity === "hard" ? t("pw_missing") : t("pw_partial")}
                    </Badge>
                    <span className="text-fg-2">{blocker.text}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          {verdict.strengths.length > 0 && (
            <div>
              <h3 className="font-serif text-xl">{t("pw_strengths")}</h3>
              <ul className="mt-2 flex flex-col gap-1 text-sm text-fg-2">
                {verdict.strengths.map((item) => (
                  <li key={item} className="flex gap-2">
                    <Check size={15} className="mt-0.5 text-ok" /> {item}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {verdict.gap_skills.length > 0 && (
            <div>
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("pw_gaps")}</p>
              <div className="mt-1.5 flex flex-wrap gap-1.5">
                {verdict.gap_skills.slice(0, 10).map((skill) => (
                  <Badge key={skill}>{skill}</Badge>
                ))}
              </div>
            </div>
          )}
        </Card>
      </div>

      {result.signals && (
        <Card>
          <h3 className="font-serif text-xl">{t("resume_signals")}</h3>
          <div className="mt-3 grid gap-3 text-sm sm:grid-cols-3">
            <div>
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("pw_signal_education")}</p>
              <p>{result.signals.education || "—"}</p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("pw_signal_years")}</p>
              <p>
                {result.signals.experience_years} → {result.signals.experience_level}
              </p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("pw_signal_skills")}</p>
              <p>{result.signals.skills.slice(0, 6).join(", ") || "—"}</p>
            </div>
          </div>
          <SourceLabel text={result.signals.source} />
        </Card>
      )}

      {result.bridges.length > 0 && (
        <section id="bridges">
          <h2 className="font-serif text-2xl">{t("pw_bridges")}</h2>
          <AnimatedGroup className="mt-3 grid gap-3 md:grid-cols-2">
            {result.bridges.map((bridge) => (
              <Card key={bridge.title}>
                <div className="flex items-start gap-3">
                  <span className="mt-0.5 grid h-8 w-8 place-items-center rounded-lg bg-accent/15 text-accent">
                    <GraduationCap size={17} />
                  </span>
                  <div>
                    <h3 className="font-medium text-fg">{bridge.title}</h3>
                    <p className="mt-0.5 text-sm text-fg-2">{bridge.why}</p>
                    <dl className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-xs text-fg-3">
                      <div>
                        <dt>{t("pw_bridge_duration")}</dt>
                        <dd className="text-fg-2">{bridge.duration}</dd>
                      </div>
                      <div>
                        <dt>{t("pw_bridge_cost")}</dt>
                        <dd className="text-fg-2">{bridge.cost_inr}</dd>
                      </div>
                      <div>
                        <dt>{t("pw_bridge_eligibility")}</dt>
                        <dd className="text-fg-2">{bridge.eligibility}</dd>
                      </div>
                      <div>
                        <dt>{t("pw_bridge_entrance")}</dt>
                        <dd className="text-fg-2">{bridge.entrance}</dd>
                      </div>
                    </dl>
                    {bridge.career_id && (
                      <Link
                        href={`/careers/${bridge.career_id}`}
                        className="mt-2 inline-flex items-center gap-1 text-xs text-accent hover:underline"
                      >
                        {t("cr_open")} <ArrowRight size={12} />
                      </Link>
                    )}
                    <SourceLabel text={bridge.source} />
                  </div>
                </div>
              </Card>
            ))}
          </AnimatedGroup>
        </section>
      )}

      {result.open_doors.length > 0 && (
        <Card>
          <h3 className="flex items-center gap-2 font-serif text-xl">
            <Info size={18} className="text-accent" /> {t("pw_open_doors")}
          </h3>
          <ul className="mt-3 grid gap-2 text-sm md:grid-cols-2">
            {result.open_doors.map((door) => (
              <li key={door.title} className="rounded-xl border border-white/8 p-3">
                <p className="text-fg">{door.title}</p>
                <p className="text-xs text-fg-3">{door.eligibility}</p>
                <p className="text-xs text-fg-3">
                  {door.entrance} · {door.duration}
                </p>
              </li>
            ))}
          </ul>
        </Card>
      )}

      <section id="plan">
        <h2 className="font-serif text-2xl">{t("pw_step_plan")}</h2>
        <p className="mt-1 text-sm text-fg-2">{result.next_step}</p>
        <div className="mt-3 flex flex-col gap-3">
          {result.plan.phases.map((phase, index) => (
            <InView key={phase.phase} delay={index * 0.03}>
              <Card>
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div>
                    <Badge tone="accent">{t("pw_phase").replace("{n}", String(phase.phase))}</Badge>
                    <p className="mt-1.5 font-medium text-fg">{phase.action}</p>
                  </div>
                  <p className="text-xs text-fg-3">
                    {t("pw_weeks_label")
                      .replace("{weeks}", String(phase.weeks))
                      .replace("{hours}", String(phase.hours))}{" "}
                    · {phase.label}
                  </p>
                </div>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {phase.focus_skills.map((skill) => (
                    <Badge key={skill}>{skill}</Badge>
                  ))}
                </div>
                {phase.resources.length > 0 && (
                  <div className="mt-3">
                    <p className="text-xs uppercase tracking-wide text-fg-3">{t("pw_resources")}</p>
                    <ul className="mt-1 flex flex-col gap-1 text-sm">
                      {phase.resources.map((resource) => (
                        <li key={resource.url}>
                          <a
                            href={resource.url}
                            target="_blank"
                            rel="noreferrer"
                            className="text-accent hover:underline"
                          >
                            {resource.title}
                          </a>
                          {resource.provider && <span className="text-fg-3"> · {resource.provider}</span>}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                <p className="mt-3 text-xs text-fg-3">
                  <span className="font-medium text-fg-2">{t("pw_checkpoint")}: </span>
                  {phase.checkpoint}
                </p>
              </Card>
            </InView>
          ))}
        </div>
        <SourceLabel text={result.plan.source} />
      </section>

      {result.market && (
        <Card>
          <h3 className="font-serif text-xl">{t("cd_market")}</h3>
          <div className="mt-3 grid gap-3 text-sm sm:grid-cols-4">
            <div>
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("cr_salary")}</p>
              <p>{money(result.market.salary_p50, result.market.symbol)}</p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("cr_demand")}</p>
              <p>{result.market.demand_label}</p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("cr_remote")}</p>
              <p>{result.market.remote ? "Yes" : "No"}</p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-wide text-fg-3">{t("cr_zone")}</p>
              <p>{result.target.job_zone}</p>
            </div>
          </div>
          <SourceLabel text={result.market.source} />
        </Card>
      )}

      <Ladder result={result} />
    </div>
  );
}

function Ladder({ result }: { result: PathwayResult }) {
  const { t } = useI18n();
  const groups: { key: keyof PathwayResult["ladder"]; label: string; rungs: LadderRung[] }[] = [
    { key: "entry_points", label: t("pw_ladder_entry"), rungs: result.ladder.entry_points },
    { key: "step_across", label: t("pw_ladder_across"), rungs: result.ladder.step_across },
    { key: "step_up", label: t("pw_ladder_up"), rungs: result.ladder.step_up },
  ];
  const empty = groups.every((group) => group.rungs.length === 0);
  return (
    <section id="ladder">
      <h2 className="flex items-center gap-2 font-serif text-2xl">
        <Target size={20} className="text-accent" /> {t("pw_ladder_title")}
      </h2>
      {empty ? (
        <p className="mt-2 text-sm text-fg-2">{t("pw_no_ladder")}</p>
      ) : (
        <div className="mt-3 grid gap-4 lg:grid-cols-3">
          {groups.map((group) => (
            <Card key={group.key}>
              <h3 className="text-sm font-medium uppercase tracking-wide text-fg-3">{group.label}</h3>
              <ul className="mt-2 flex flex-col gap-2 text-sm">
                {group.rungs.slice(0, 4).map((rung) => (
                  <li key={rung.id}>
                    <Link href={`/careers/${rung.id}`} className="text-fg hover:text-accent">
                      {rung.title}
                    </Link>
                    <p className="text-xs text-fg-3">
                      {t("cr_zone_n").replace("{n}", String(rung.job_zone))} · {rung.coverage}% ·{" "}
                      {rung.weeks_at_your_pace}w
                      {rung.salary_p50 ? ` · ${money(rung.salary_p50, rung.currency === "USD" ? "$" : "₹")}` : ""}
                    </p>
                  </li>
                ))}
                {group.rungs.length === 0 && <li className="text-xs text-fg-3">—</li>}
              </ul>
            </Card>
          ))}
        </div>
      )}
      {result.alternatives.length > 0 && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-4">
          <p className="text-xs uppercase tracking-wide text-fg-3">{t("pw_alternatives")}</p>
          <div className="mt-1.5 flex flex-wrap gap-1.5">
            {result.alternatives.map((rung) => (
              <Link key={rung.id} href={`/careers/${rung.id}`}>
                <Badge tone="accent">
                  {rung.title} · {rung.coverage}%
                </Badge>
              </Link>
            ))}
          </div>
        </motion.div>
      )}
      <SourceLabel text={result.sources.skills} />
    </section>
  );
}
